logging:
  level:
    '[org.carthageking]': TRACE


spring:
  #datasource:
    #url: jdbc:postgresql://localhost:5432/test_db?currentSchema=my_schema
    #driver-class-name: org.postgresql.Driver
    #username: postgres
    #password: root123@ 
  jpa:
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect 
        '[format_sql]': true